### ISSUE TITLE
Events branch triggering vercel builds

### ISSUE THREAD

**Issue by scook12** [Duranzno/meditation-app-hackathon#1]
## Issue

Seems like commits to feature branches like `events` are still triggering vercel builds. I'm not sure it's a problem since I haven't looked at the pipeline.

Is that running all the dev commits in feature branches out to the vercel-deployed app? Since it's a hackathon, developing in production is essentially the norm, but it seems like this trigger a lot of unnecessary builds.

## Solution

Maybe pull ci/cd from the feature branches? That way we can have a staging branch, run tests, then have deployments triggered by merging stage to the master trunk.

Mostly a question, it may not make a difference, idk if Vercel has limits on their free tier for automated builds.

**Comment by Duranzno** [comment]
Ok, it seems that I closed the issue whle trying to fix it. haha
It is already fixed with so it will only deploy from the (creatively named) branch "deploy"

**Comment by scook12** [comment]
Perfect, thanks for this!
