### ISSUE TITLE
blitz `useParam` hook fails to accurately return eventId

### ISSUE THREAD

**Issue by scook12** [Duranzno/meditation-app-hackathon#2]
## Issue

So, in the scaffolded resources created by `blitz generate`, we get mutations, pages, queries, and a form component.

The way dynamic routing is done in the next router (and by extension the blitz router) is via the file system filename syntax. For events, an example is the [eventId].tsx under /app/events/pages/events/ which should display the information for an event identified via event.id.

The scaffolded Event component for the [eventId] module makes use of the useParam hook which should return the id of the component, but it doesn't. The page throws 404 and if you log the result of useParam to the console, it's an empty string.

## Expectation

The /events/event-id-here path should return the Event component.

## Workaround

For now, I'm making use of a trick I picked up in next.js to make the query work. Instead of `useParam`, I take the `router` object returned by `useRouter` and slice the event.id parameter out of the URL that the router is pushing to.

e.g.
```
const router = useRouter()

const eventId = router.asPath.split("/events/")[1] 
const [event] = useQuery(getEvent, {where: {id: eventId}})
```

This won't work though once we migrate the individual event view into a modal component that doesn't need a separate page to view because the router won't be receiving the eventId anymore. I'll need someway to grab that Id from the card in the events index.

thoughts? anyone else run into issues with the useParam hook?

**Comment by scook12** [comment]
Never mind, figured it out.

The issue was that the scaffolded mutation components/forms don't pass accurate parameters to the `useParam` hook.

When you call `blitz generate all model_name` the EditModelName, or CreateModelName, or whatever form page doesn't necessarily adjust it's call to the schema you create for that model.

Instead, it assumes the param is actually called "id" in the URL, but in my case the param was actually "eventId".

Fix:

```
const eventId = useParam("eventId", "string")
// instead of: const eventId = useParam("id", "number")
```

Ironically, the hack with the router is essentially the same thing as the `useParam` hook, just less stable. I'll still need to find a way to pass the eventId to the modal component since `useParam` also relies on the URL...

**Comment by Duranzno** [comment]
Oh, I just fixed that same thing on the master branch as I had merged some of your changes to master to create the skeleton haha
